version: "3"
services:
  node-red:
    build: node-red/.
    restart: always
    ports:
      - "127.0.0.1:1880:1880"
    volumes:
      - ./node-red/data:/data
    user: root
  mosquitto:
    image: "eclipse-mosquitto:2.0.14"
    restart: always
    ports:
      - 1883:1883
    expose:
      - 1883
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    user: root
  influxdb:
    image: "influxdb:1.8.10"
    restart: always
    expose:
      - 8086
    volumes:
      - ./influxdb/db:/var/lib/influxdb
      - ./influxdb/init:/docker-entrypoint-initdb.d # startup scripts
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
    user: root

