FROM nodered/node-red:1.0.3-4-12
RUN npm install node-red-node-mongodb@0.0.14
RUN npm install node-red-dashboard@2.19.4
RUN npm install node-red-contrib-telegrambot@7.1.1
RUN npm install node-red-contrib-influxdb@0.4.0
RUN npm install node-red-contrib-throttle@0.1.6
RUN npm install node-red-contrib-socketio@1.0.7