FROM nodered/node-red:2.2.2-12
RUN npm i node-red-node-mongodb@0.0.14
RUN npm i node-red-dashboard@2.19.4
RUN npm i node-red-contrib-telegrambot@7.1.1
RUN npm i node-red-contrib-influxdb@0.4.0
RUN npm i node-red-contrib-throttle@0.1.6
RUN npm i node-red-contrib-socketio@1.0.7
RUN npm i node-red-node-random
RUN npm i node-red-node-suncalc
RUN npm i node-red-node-ui-table

